PROGRAM PrintEnv(INPUT, OUTPUT);
USES 
  GPC;
BEGIN {PrintHello}
  WRITELN('Content-Type: text/plain');
  WRITELN;
  WRITELN('QUERTY_STRING: ', GetEnv('QUERY_STRING'));
  WRITELN('REQUEST_METHOD: ', GetEnv('REQUEST_METHOD'));
  WRITELN('CONTENT_LENGTH: ', GetEnv('CONTENT_LENGTH'));
  WRITELN('HTTP_USER_AGENT: ', GetEnv('HTTP_USER_AGENT'));
  WRITELN('HTTP_HOST: ', GetEnv('HTTP_HOST'))
END. {PrintHello}